# -*- coding: utf-8 -*-
"""Audit classifier v3: units/dimensions signal layer + chapter rules.
   Rule form: ([[and1,and2,...], [alt2...], ...], chapter, family, status)
   A rule matches if ANY alternative list has ALL its substrings present (lowercased)."""
import re, collections

def parse():
    lines = open('/home/user/agniveer/Master_Physics_All_Papers.txt', encoding='utf-8').read().split('\n')
    paper=None; cur_qid=None; cur_lines=[]; cur_ans='?'; out=[]
    def close():
        nonlocal cur_qid, cur_lines, cur_ans
        if cur_qid is not None:
            q = re.sub(r'\s+',' ',' '.join(cur_lines)).strip()
            q = re.sub(r'=+\s*$','',q).strip()
            out.append((paper, cur_qid, q, cur_ans))
        cur_qid=None; cur_lines=[]; cur_ans='?'
    def is_option(ln):
        s=ln.strip()
        return bool(re.match(r'^\([A-Da-d]\)',s) or re.match(r'^[1-4]\.\s',s) or re.match(r'^[A-Da-d]\.\s',s))
    for ln in lines:
        m=re.match(r'^PAPER\s+(\d+)',ln)
        if m: close(); paper=f"P{m.group(1)}"; continue
        m=re.match(r'^(Q\d+)\.\s*(.*)$',ln)
        if m: close(); cur_qid=m.group(1); cur_lines=[m.group(2)]; continue
        if cur_qid is not None:
            am=re.match(r'^\s*Answer:\s*([A-Da-d])',ln)
            if am: cur_ans=am.group(1).upper(); continue
            if is_option(ln): continue
            if ln.strip(): cur_lines.append(ln.strip())
    close()
    return out

out = parse()

# ---------------------------------------------------------------- LAYER 1: units/dimensions
U_SIGNALS = ['dimension','dimensional','unit of','si unit','cgs','mks','tesla','gauss','henry',
             'kwh','kilowatt-hour','kilowatt hour','dyne','fahrenheit','°f','pico','micron',
             'light year','light-year','specific gravity','dimensionless','unitless','unit-less',
             'unit but','has unit','no dimension','same unit','same dimension','derived unit',
             'base unit','fundamental quantity','fundamental quantities','mechanical equivalent of heat',
             'equivalent increase', 'not a physical quantity', 'vector quantity', 'scalar quantity',
             'stefan','boltzman','luminance','pole strength','unit is','units of']

def unit_dim(q):
    ql=q.lower()
    if 'nit' in ql and 'unit' not in ql: pass  # never bare 'nit'
    for s in U_SIGNALS:
        if s in ql:
            return True
    return False

def u_family(q):
    ql=q.lower()
    # value/memorize constants
    if 'stefan' in ql or 'boltzman' in ql: return ('Stefan-Boltzmann value','C')
    if 'mechanical equivalent of heat' in ql: return ('Mechanical equiv heat','C')
    if 'pole strength' in ql: return ('Pole strength unit','C')
    if 'cgs unit of electric dipole' in ql or ('cgs' in ql and 'dipole' in ql): return ('Dipole moment CGS','C')
    # temperature conversion
    if 'fahrenheit' in ql or '°f' in ql or ' f scale' in ql: return ('F<->C conversion','C')
    # dimension-specific
    if 'dimension' in ql or 'dimensional' in ql:
        if 'energy' in ql: return ('Dimension of a quantity','A')
        if 'pressure' in ql: return ('Dimension of a quantity','A')
        if 'angular momentum' in ql: return ('Dimension of a quantity','A')
        if 'planck' in ql or 'plank' in ql: return ('Planck h dimension','A')
        if 'mutual induct' in ql: return ('Mutual inductance dim','A')
        if 'resistivity' in ql: return ('Resistivity dim/unit','A')
        if 'viscos' in ql or 'stoke' in ql: return ('Viscosity (Stokes)','A')
        if 'van der waals' in ql: return ('van der Waals a dim','A')
        if 'gravitational constant' in ql: return ('G dimension','A')
        if 'magnetic field' in ql: return ('B field dimension','B')
        if 'electrostatic potential' in ql: return ('Potential dimension','B')
        if 'ratio of the dimension of planck' in ql or ('planck' in ql and 'ratio' in ql): return ('Dimension ratio h/I','B')
        if 'physical constant has dimension' in ql or 'dimensions of a physical quantity' in ql: return ('Dimension of power','A')
        if 'not a derived' in ql or 'derived unit' in ql: return ('Base vs derived','A')
        if 'same dimension' in ql or 'same dimensional' in ql: return ('Same-dimension pairs','A')
        return ('Dimension of a quantity','A')
    # unit-specific
    if 'unitless' in ql or 'unit-less' in ql or 'no dimension' in ql or 'dimensionless' in ql: return ('Dimensionless quantity','A')
    if 'unit but' in ql or ('has unit' in ql and 'dimension' in ql): return ('Unitless with unit','A')
    if 'specific gravity' in ql: return ('Dimensionless quantity','A')
    if 'same unit' in ql: return ('Same-dimension pairs','A')
    if 'tesla' in ql or 'gauss' in ql: return ('B field unit','A')
    if 'henry' in ql: return ('Henry unit','A')
    if 'kwh' in ql or 'kilowatt' in ql: return ('Unit conversion kWh','A')
    if 'dyne' in ql or 'cgs unit of force' in ql or ('si unit and cgs' in ql) or ('si and cgs' in ql): return ('N->dyne','A')
    if 'pico' in ql or 'micron' in ql: return ('pm->micron','A')
    if 'light year' in ql or 'light-year' in ql: return ('Light-year','A')
    if 'unit of static friction' in ql: return ('Friction unit','A')
    if 'unit of current' in ql or 'si unit of current' in ql: return ('Unit of current','A')
    if 'permittivity' in ql and 'unit' in ql: return ('Permittivity unit','A')
    if 'permeability' in ql and 'unit' in ql: return ('Permeability value','A')
    if 'coefficient of viscosity' in ql: return ('Viscosity unit','B')
    if 'density of a material in si' in ql or ('128 kg' in ql and 'density' in ql): return ('Density unit conversion','A')
    if 'unit of energy' in ql: return ('Energy unit','A')
    if 'not a derived unit' in ql or 'derived unit' in ql: return ('Base vs derived','A')
    if 'fundamental quantit' in ql: return ('New fundamental quantities','C')
    if 'equivalent increase' in ql or ('kelvin' in ql and 'celsius' in ql): return ('Celsius-Kelvin interval','A')
    if 'not a physical quantity' in ql: return ('kg = unit not quantity','A')
    if 'vector quantity' in ql: return ('Vector quantity','A')
    if 'scalar quantity' in ql: return ('Scalar quantity','A')
    if 'equivalent increase' in ql or ('kelvin' in ql and 'celsius' in ql): return ('Celsius-Kelvin interval','A')
    return ('Unit misc','A')

# ---------------------------------------------------------------- LAYER 2: chapter rules
R=[]
def rule(alt, ch, fam, st): R.append((alt,ch,fam,st))

# CH2 KINEMATICS
rule([['1st, 2nd, 3rd'],['distances travelled by a freely'],['ratio of the distances']], 'Ch2 Kinematics','1:3:5:7 ratio','A')
rule([['slope of velocity'],['slope of a velocity'],['slope of the velocity'],['slope of velocity-time']], 'Ch2 Kinematics','Graph slope','A')
rule([['from rest to 20 m/s'],['car accelerates uniformly']], 'Ch2 Kinematics','Equations of motion','A')
rule([['heights h and 2h'],['dropped from heights'],['two balls are dropped']], 'Ch2 Kinematics','t∝√h','A')
rule([['αt3'],['initial velocity of the object']], 'Ch2 Kinematics','Polynomial s(t)','A')
rule([['projectile']], 'Ch2 Kinematics','Projectile','A')
rule([['maximum height of the'],['initial velocity of a projectile']], 'Ch2 Kinematics','Projectile H∝u²','A')
rule([['time of flight'],['thrown vertically'],['10 m/s']], 'Ch2 Kinematics','Projectile T','A')
rule([['circular path with acceleration'],['velocity gets doubled'],['velocity becomes double']], 'Ch2 Kinematics','a∝v²','A')
rule([['angular velocity (ω) and linear'],['angular velocity and linear'],['angular velocity and the linear']], 'Ch2 Kinematics','v=ωr','A')
rule([['angular displacement']], 'Ch2 Kinematics','Angular displacement','A')
rule([['one-third of the distance'],['average speed of the car'],['average velocity of the car']], 'Ch2 Kinematics','Avg speed segments','B')
rule([['motorcycle'],['54 kmph'],['54 km/h']], 'Ch2 Kinematics','km/h conversion','B')
rule([['semicircular']], 'Ch2 Kinematics','Semicircle displacement','A')
rule([['v2 = a + bx'],['v2= a + bx'],['v2 = a+bx'],['v2= a+bx'],['v2=a+bx']], 'Ch2 Kinematics','a=v dv/dx','A')
rule([['8 + 12t'],['retardation']], 'Ch2 Kinematics','Retardation','A')
rule([['xt2'],['xt²'],['at t = 4 s']], 'Ch2 Kinematics','Polynomial a=2x','A')
rule([['30 m/s due east'],['due east']], 'Ch2 Kinematics','Equations -a','A')
rule([['coefficient of restitution'],['bounces again']], 'Ch2 Kinematics','Restitution','C')
rule([['escalator']], 'Ch2 Kinematics','Escalator','C')
rule([['falling freely'],['free fall'],['freely under the influence']], 'Ch2 Kinematics','Free-fall concept','A')
rule([['centripetal']], 'Ch2 Kinematics','Centripetal','A')
rule([['ball is thrown'],['maximum height'],['20 m/s']], 'Ch2 Kinematics','Projectile H','A')
rule([['u2 sin'],['u2 sin2']], 'Ch2 Kinematics','Projectile H∝u²','A')

# CH3 LAWS OF MOTION
rule([['not a force']], 'Ch3 Laws','Impulse not force','A')
rule([['passengers'],['bus suddenly starts'],['bus starts']], 'Ch3 Laws','Inertia vs 3rd law','A')
rule([['boat']], 'Ch3 Laws','3rd law boat','A')
rule([['impulse']], 'Ch3 Laws','Impulse','A')
rule([['bounces back with the same velocity'],['bounces back with same']], 'Ch3 Laws','Impulse bounce','A')
rule([['recoil'],['bullet']], 'Ch3 Laws','Recoil','A')
rule([['3000 units of momentum'],['new momentum']], 'Ch3 Laws','Momentum ∝ v','A')
rule([['four times of its initial'],['kinetic energy of a body becomes four'],['kinetic energy becomes four']], 'Ch3 Laws','K-p relation','A')
rule([['relationship between kinetic energy and linear momentum'],['kinetic energy and linear momentum']], 'Ch3 Laws','K-p relation','A')
rule([['90 n'],['unbalanced force']], 'Ch3 Laws','F=ma mass','A')
rule([['8 tonnes']], 'Ch3 Laws','F=ma force','A')
rule([['100 cm/s']], 'Ch3 Laws','F=ma cm->m','A')
rule([['coefficient of static'],['co-efficient of static'],['static friction between']], 'Ch3 Laws','a=μsg','A')
rule([['force of friction']], 'Ch3 Laws','Friction statement','A')
rule([['heavier in a lift'],['lift when']], 'Ch3 Laws','Lift apparent weight','C')
rule([["newton's first"],['first law of motion gives']], 'Ch3 Laws','1st law concept','A')
rule([['3 kn and 4 kn'],['resultant']], 'Ch3 Laws','Vector addition','C')
rule([['minimum number of forces'],['zero resultant']], 'Ch3 Laws','Min forces','C')
rule([['equilibrium']], 'Ch3 Laws','Equilibrium conditions','C')
rule([['rate of change of linear momentum'],['change in velocity from 2 m/s']], 'Ch3 Laws','F=dp/dt','A')
rule([['cushioned'],['high jump']], 'Ch3 Laws','Airbag','A')
rule([['measure of its inertia'],['measure of inertia']], 'Ch3 Laws','Mass=inertia','A')
rule([['force produces change of momentum'],['isolated system']], 'Ch3 Laws','Momentum concepts','A')
rule([['cricket ball'],['fielder']], 'Ch3 Laws','Impulse','A')
rule([['force is not electromagnetic'],['forces is not electromagnetic']], 'Ch3 Laws','Force not electromagnetic','C')
rule([['frictionless fixed pulley'],['passes over a frictionless']], 'Ch3 Laws','Atwood pulley','C')
rule([['angle between two vectors'],['angle between the two vectors']], 'Ch3 Laws','Angle between vectors','C')
rule([['velocity v and mass m'],['relationship between velocity'],['momentum is conserved']], 'Ch3 Laws','v vs m (p conserved)','A')
rule([['same kinetic energy'],['more momentum']], 'Ch3 Laws','Same KE momentum','A')
rule([['25%','momentum']], 'Ch3 Laws','K-p relation (25%)','A')

# CH4 WORK ENERGY POWER
rule([['work done by a force'],['work done by the force'],['displaced by'],['force displaces']], 'Ch4 WorkEnergy','Dot product','A')
rule([['spring']], 'Ch4 WorkEnergy','Spring energy','A')
rule([['retards the motion'],['retarding']], 'Ch4 WorkEnergy','Retarding sign','A')
rule([['3 a x'],['3ax'],['moving along x axis'],['displaces from x = 0']], 'Ch4 WorkEnergy','Variable force','A')
rule([['pump']], 'Ch4 WorkEnergy','Power mgh/t','A')
rule([['ratio of the power'],['80 kg']], 'Ch4 WorkEnergy','Power mgh/t','A')
rule([['rebounds'],['80 %'],['80%']], 'Ch4 WorkEnergy','PE∝h','A')
rule([['conservative force']], 'Ch4 WorkEnergy','Conservative force','A')
rule([['1000 n force'],['kinetic energy has been changed'],['kinetic energy has been']], 'Ch4 WorkEnergy','W=Fs','A')
rule([['athlete'],['60 kg']], 'Ch4 WorkEnergy','KE estimate','A')
rule([['energy stored in a stretched wire'],['energy stored']], 'Ch4 WorkEnergy','Wire energy ½YS²','B')
rule([['lifts a box'],['gravitational force']], 'Ch4 WorkEnergy','Work by gravity','A')
rule([['elastic potential energy density'],['energy density']], 'Ch4 WorkEnergy','Energy density ½σε','B')
rule([['area under force-displacement'],['area under force displacement']], 'Ch4 WorkEnergy','F-s graph area = work','A')
rule([['force acting on a moving particle does not work'],['does not work on it']], 'Ch4 WorkEnergy','Force perpendicular no work','A')
rule([['power is given by'],['f, v, and power'],['p = f'],['power p']], 'Ch4 WorkEnergy','P=FV','A')
rule([['negative work'],['positive work']], 'Ch4 WorkEnergy','Work sign','A')

# CH5 ROTATIONAL
rule([['ring of mass'],['tangent to the circle']], 'Ch5 Rotational','MI ring tangent','A')
rule([['disc about a diameter'],['diameter is i']], 'Ch5 Rotational','MI disc 6I','A')
rule([['perpendicular to its plane']], 'Ch5 Rotational','MI disc centre','A')
rule([['moment of inertia depends'],['moment of inertia of a rigid body']], 'Ch5 Rotational','MI depends','A')
rule([['radius of gyration']], 'Ch5 Rotational','Radius of gyration','A')
rule([['circular ring of mass'],['rotations per second']], 'Ch5 Rotational','L=Iω numeric','A')
rule([['centre of mass of a uniform cube']], 'Ch5 Rotational','CM uniform body','B')
rule([['centre of mass of three masses'],['find the centre of mass'],['center of mass of three']], 'Ch5 Rotational','CM position','B')
rule([['mutual gravitational'],['towards each other'],['velocity of their centre of mass'],['velocity of their center of mass']], 'Ch5 Rotational','CM velocity','A')
rule([['torque depends']], 'Ch5 Rotational','Torque depends','A')
rule([['torque applied'],['point located']], 'Ch5 Rotational','Torque cross product','C')
rule([['moment of inertia doubles'],['angular speed']], 'Ch5 Rotational','L conserved','A')
rule([['dumbbells'],['rotating table'],['withdraws his hands'],['withdraws his arms']], 'Ch5 Rotational','L conserved','A')
rule([['areal velocity'],['kepler']], 'Ch5 Rotational','Kepler 2nd','A')
rule([['angular acceleration of a particle']], 'Ch5 Rotational','α in UCM','B')
rule([['direction of centripetal']], 'Ch5 Rotational','Centripetal direction','B')
rule([['incorrect regarding centre of mass'],['incorrect regarding center of mass']], 'Ch5 Rotational','CM statements','B')

# CH6 GRAVITATION
rule([['four times the mass'],['mass is 1/7'],['gravitational acceleration of the planet'],['mass of a planet']], 'Ch6 Gravitation','g∝M/R²','A')
rule([['radius of the earth is reduced'],['reduced by 2/3'],['radius is reduced by 1%'],['2/3rd']], 'Ch6 Gravitation','g∝1/R²','A')
rule([['reduces by 75'],['height at which acceleration due to gravity'],['acceleration due to gravity becomes']], 'Ch6 Gravitation','g vs height exact','B')
rule([['coal mine'],['sea level'],['top of the mountain']], 'Ch6 Gravitation','Weight vs location','A')
rule([['center of the earth'],['centre of the earth']], 'Ch6 Gravitation','Weight at centre','A')
rule([['equator to the poles'],['equator to poles'],['poles to equator'],['poles to the equator']], 'Ch6 Gravitation','g pole/equator','A')
rule([['escape velocity'],['escape']], 'Ch6 Gravitation','Escape velocity','A')
rule([['unequal mass']], 'Ch6 Gravitation','Equal escape M/R','A')
rule([['satellite']], 'Ch6 Gravitation','Satellite','A')
rule([['semi-major axis'],['semi major axis']], 'Ch6 Gravitation','Kepler semi-major','A')
rule([['weightlessness'],['astronaut']], 'Ch6 Gravitation','Weightless','A')
rule([['variation of acceleration due to gravity'],['g with distance x']], 'Ch6 Gravitation','g vs r graph','A')
rule([['ratio of g/g'],['g/g will be'],['ratio of the value of g']], 'Ch6 Gravitation','G/g ratio','A')
rule([['mass of the earth']], 'Ch6 Gravitation','M=gR²/G','A')
rule([['9.8 m/s'],['10 kg object']], 'Ch6 Gravitation','Moon weight','A')
rule([['depends on the mass of the earth'],['mass of the earth.']], 'Ch6 Gravitation','g depends on M','A')
rule([['radii of two planets'],['ratio of the radii of two planets'],['densities']], 'Ch6 Gravitation','g∝ρR','B')
rule([['force of attraction between two objects'],['masses m1 and m2']], 'Ch6 Gravitation','F=GMm/r2','A')
rule([['escape velocity','11.2'],['11.2']], 'Ch6 Gravitation','Escape velocity value','A')

# CH7 BULK MATTER
rule([['slope of the linear portion'],['stress-strain'],['stress strain'],['young']], 'Ch7 Bulk','Young modulus','A')
rule([['poisson']], 'Ch7 Bulk','Poisson ratio','A')
rule([['breaking stress']], 'Ch7 Bulk','Breaking stress','C')
rule([['stress generated'],['pulled away']], 'Ch7 Bulk','Stress wire','A')
rule([['maximum elasticity'],['elasticity']], 'Ch7 Bulk','Max elasticity','C')
rule([['modulus of rigidity']], 'Ch7 Bulk','Modulus rigidity','C')
rule([['resist permanent changes']], 'Ch7 Bulk','Elasticity definition','B')
rule([['gauge pressure']], 'Ch7 Bulk','Gauge pressure','A')
rule([['excess pressure'],['soap bubble'],['pressure inside']], 'Ch7 Bulk','Excess pressure','A')
rule([['surface tension'],['spherical shape'],['hair'],['cling']], 'Ch7 Bulk','Surface tension','A')
rule([['meniscus'],['angle of contact'],['contact angle']], 'Ch7 Bulk','Contact angle','A')
rule([['terminal velocity']], 'Ch7 Bulk','Terminal velocity','A')
rule([['drops combine'],['drops of water'],['eight equal drops'],['27 equal droplets'],['27 droplets']], 'Ch7 Bulk','Drops volume->r','B')
rule([['stoke'],['viscous force']], 'Ch7 Bulk','Stokes η','A')
rule([['viscosity of a liquid depends'],['coefficient viscosity'],['viscosity of the liquid']], 'Ch7 Bulk','Viscosity depends','C')
rule([['ice melts'],['filled to the brim'],['ice cube']], 'Ch7 Bulk','Ice melts brim','A')
rule([['floats in water'],['cube floats'],['outside the water']], 'Ch7 Bulk','Float fraction','B')
rule([['fraction of a ball floating'],['floating inside']], 'Ch7 Bulk','Float fraction','B')
rule([['loss of weight'],['weight of the fluid displaced'],['archimedes']], 'Ch7 Bulk','Archimedes','A')
rule([['venturi'],['manometer']], 'Ch7 Bulk','Venturi','A')
rule([['bernoulli'],['continuity']], 'Ch7 Bulk','Bernoulli/continuity','A')
rule([['pascal']], 'Ch7 Bulk','Pascal law','A')
rule([['metal ball just passes'],['only the ball is heated']], 'Ch7 Bulk','Thermal expansion','C')
rule([['linear, area and volume expansion'],['areal expansion'],['volume expansion'],['cubical expansion'],['linear expansion']], 'Ch7 Bulk','Thermal expansion αβγ','C')
rule([['thermometer works']], 'Ch7 Bulk','Thermometer expansion','C')
rule([['cooled down suddenly'],['breaks']], 'Ch7 Bulk','Thermal stress glass','C')
rule([['240 ml'],['heated from'],['new volume'],['volume by 40'],['298 k'],['atmospheric pressure']], 'Ch7 Bulk','Charles V∝T','A')
rule([['pv = constant'],['pressure and volume']], 'Ch7 Bulk','Boyle name','C')
rule([['not a part of ideal gas'],['ideal gas law']], 'Ch7 Bulk','Ideal gas law','A')
rule([['maximum specific heat'],['wood absorbs'],['specific heat']], 'Ch7 Bulk','Calorimetry','C')
rule([['capillary']], 'Ch7 Bulk','Capillary rise','C')
rule([['viscosity of the liquid'],['liquid stops'],['liquid will come to rest']], 'Ch7 Bulk','Viscosity stops liquid','A')
rule([['stirred'],['bucket']], 'Ch7 Bulk','Viscosity stops liquid','A')

# CH8 THERMODYNAMICS
rule([['zeroth'],['defines the concept temperature']], 'Ch8 Thermo','Zeroth law','A')
rule([['first law'],['law of thermodynamics']], 'Ch8 Thermo','First law','A')
rule([['energy conservation'],['energy is conserved']], 'Ch8 Thermo','First law = energy conservation','A')
rule([['isothermal']], 'Ch8 Thermo','Isothermal','A')
rule([['adiabatic']], 'Ch8 Thermo','Adiabatic','A')
rule([['isochoric']], 'Ch8 Thermo','Isochoric W=0','C')
rule([['isobaric']], 'Ch8 Thermo','Isobaric','C')
rule([['refrigerator'],['coefficient of performance']], 'Ch8 Thermo','Refrigerator COP','C')
rule([['carnot']], 'Ch8 Thermo','Carnot','A')
rule([['second law']], 'Ch8 Thermo','Second law entropy','A')
rule([['entropy']], 'Ch8 Thermo','Entropy','A')
rule([['cyclic integral'],['cyclic process']], 'Ch8 Thermo','Cyclic ΔU=0','A')
rule([['path function']], 'Ch8 Thermo','Path function','B')
rule([['efficiency']], 'Ch8 Thermo','Carnot W','A')
rule([['heat absorbed'],['heat given'],['heat supplied'],['heat taken from'],['heat rejected'],['heat added'],['heat transferred']], 'Ch8 Thermo','First law cal','A')
rule([['200 j of work is done on the gas']], 'Ch8 Thermo','Adiabatic ΔU','A')
rule([['thermodynamic'],['internal energy']], 'Ch8 Thermo','First law','A')
rule([['change in internal energy'],['increase in internal energy'],['decrease in internal energy'],['internal energy change'],['internal energy of the system']], 'Ch8 Thermo','First law','A')
rule([['increased without giving heat'],['increase the temperature'],['temperature can be increased']], 'Ch8 Thermo','Raise T without heat','A')
rule([['graph of pressure versus volume'],['pressure versus volume for an ideal gas'],['pressure-volume'],['pressure volume']], 'Ch8 Thermo','P-V graph adiabatic/isothermal','A')
rule([['work done by the gas'],['work done by the system'],['work done in a thermodynamic']], 'Ch8 Thermo','First law','A')
rule([['heat converted into work'],['work done by the engine']], 'Ch8 Thermo','Carnot W','A')
rule([['sink'],['source temperature']], 'Ch8 Thermo','Carnot source/sink','A')

# CH9 KINETIC THEORY
rule([['rms speed'],['rms speeds'],['root mean square speed'],['root-mean-square speed']], 'Ch9 Kinetic','rms ∝√T','C')
rule([['translational kinetic energy'],['2e = 3'],['e and its temperature'],['kinetic energy of the molecules']], 'Ch9 Kinetic','KE-T relation','A')
rule([['specific heat of gases'],['cp/cv'],['two specific heat'],['cp and cv'],['diatomic']], 'Ch9 Kinetic','γ=Cp/Cv','A')
rule([['velocity of sound'],['332 m/s'],['pressure of a gas is taken double']], 'Ch9 Kinetic','Sound speed vs P','A')
rule([['degrees of freedom']], 'Ch9 Kinetic','Degrees of freedom','A')
rule([['monoatomic']], 'Ch9 Kinetic','γ=Cp/Cv','A')
rule([['kinetic energy of molecule'],['pressure of an ideal gas is increased'],['temperature constant']], 'Ch9 Kinetic','KE vs T','A')

# CH10 OSCILLATIONS & WAVES
rule([['mean position']], 'Ch10 Osc/Waves','SHM mean','A')
rule([['half of the amplitude']], 'Ch10 Osc/Waves','SHM x=A/2','A')
rule([['maximum acceleration and maximum velocity'],['ratio of the magnitude']], 'Ch10 Osc/Waves','amax/vmax','A')
rule([['harmonic oscillator'],['angular speed']], 'Ch10 Osc/Waves','ω=√(a/x)','A')
rule([['pendulum']], 'Ch10 Osc/Waves','Pendulum T∝√L','A')
rule([['maximum acceleration at']], 'Ch10 Osc/Waves','SHM extreme','A')
rule([['energy of a particle executing']], 'Ch10 Osc/Waves','SHM energy','A')
rule([['amplitude is doubled'],['amplitude of a simple harmonic']], 'Ch10 Osc/Waves','SHM energy ∝A²','A')
rule([['force acting on a particle of mass'],['performing simple harmonic']], 'Ch10 Osc/Waves','T=2π√(m/k)','A')
rule([['maximum instantaneous velocity'],['timeperiod']], 'Ch10 Osc/Waves','vmax=2πA/T','A')
rule([['x = a/2 from the mean'],['time taken by the pendulum']], 'Ch10 Osc/Waves','t for x=a/2','C')
rule([['not an example of simple harmonic']], 'Ch10 Osc/Waves','SHM examples','B')
rule([['phase difference between the velocity and the acceleration'],['phase difference between velocity and acceleration']], 'Ch10 Osc/Waves','v-a phase','C')
rule([['equations of two waves'],['phase difference between two waves']], 'Ch10 Osc/Waves','Phase diff waves','C')
rule([['transverse wave passing'],['maximum velocity of the particle in a wave']], 'Ch10 Osc/Waves','Wave v=Aω','A')
rule([['velocity of sound is maximum'],['sound waves travel faster'],['sound waves are not affected'],['sound travels'],['speed of sound']], 'Ch10 Osc/Waves','Sound in media','A')
rule([['electromagnetic waves and sound'],['differentiate the electromagnetic'],['light wave and sound wave']], 'Ch10 Osc/Waves','Polarization','B')
rule([['bats']], 'Ch10 Osc/Waves','Bats','A')
rule([['energy is not transferred']], 'Ch10 Osc/Waves','Stationary wave','C')
rule([['longitudinal wave']], 'Ch10 Osc/Waves','Longitudinal wave','A')
rule([['relation between frequency'],['velocity of propagation'],['v = f'],['v=f'],['frequency of sound recorded'],['frequency of sound'],['source of sound of frequency']], 'Ch10 Osc/Waves','v=fλ','A')
rule([['propagation constant'],['angular wave number'],['wave number']], 'Ch10 Osc/Waves','Wave number k','C')
rule([['700 m/s']], 'Ch10 Osc/Waves','v=fλ numeric','A')
rule([['relationship is incorrect'],['k is wave number']], 'Ch10 Osc/Waves','Wave relations','B')
rule([['echo']], 'Ch10 Osc/Waves','Echo','C')
rule([['intensity of light depends'],['intensity of a wave']], 'Ch10 Osc/Waves','Intensity vs amplitude','C')
rule([['moon','sound'],['sound','vacuum']], 'Ch10 Osc/Waves','No sound in vacuum','A')
rule([['simple harmonic motion'],['shm'],['s.h.m']], 'Ch10 Osc/Waves','SHM equation a=-w2x','A')
rule([['simple pendulum'],['time period']], 'Ch10 Osc/Waves','Pendulum T∝√L','A')
rule([['frequency of the pendulum'],['ratio of length of two simple pendulums'],['length of a simple pendulum is increased']], 'Ch10 Osc/Waves','Pendulum T∝√L','A')

# CH11 ELECTROSTATICS
rule([['electrostatic force between two charges'],['force between two charges'],['force between the two charges'],['two charges are placed in vacuum'],['dielectric'],['force between the charges'],['two equal charges placed']], 'Ch11 Electrostatics','Coulomb force','A')
rule([['ratio of the force exerted on charge']], 'Ch11 Electrostatics','Equal force 3rd law','A')
rule([['q3 is brought']], 'Ch11 Electrostatics','F12 unchanged','A')
rule([['magnitude of charge cannot'],['charge cannot be produce']], 'Ch11 Electrostatics','Charge quantization','C')
rule([['charge at rest produces']], 'Ch11 Electrostatics','Rest charge','A')
rule([['work done on moving a charge'],['work done in carrying a charge'],['work done to move a charge']], 'Ch11 Electrostatics','V=W/q','C')
rule([['dipole depends upon distance'],['due to a dipole']], 'Ch11 Electrostatics','Dipole E,V vs r','C')
rule([['electric dipole is formed'],['angular frequency']], 'Ch11 Electrostatics','Dipole ω','A')
rule([['potential inside a hollow sphere'],['potential at any point inside'],['potential inside the conductor'],['potential at a point p'],['potential at the center'],['potential at a point']], 'Ch11 Electrostatics','V of sphere','A')
rule([['electric field inside the conductor'],['field inside the conductor']], 'Ch11 Electrostatics','E inside conductor','A')
rule([['equipotential']], 'Ch11 Electrostatics','Equipotential','B')
rule([['spherical conductor is placed in an external'],['external electric field']], 'Ch11 Electrostatics','Charge on conductor','B')
rule([['electric flux']], 'Ch11 Electrostatics','Electric flux','B')
rule([['capacitor'],['capacitance'],['parallel plate']], 'Ch11 Electrostatics','Capacitor','A')
rule([['capacitors each of capacity'],['capacitors']], 'Ch11 Electrostatics','Capacitor combo','A')
rule([['vertices of an equilateral triangle'],['work done required to arrange']], 'Ch11 Electrostatics','PE of charge system','C')
rule([['surface charge density'],['spherical shell']], 'Ch11 Electrostatics','Shell σ','C')
rule([['two plates are at potentials'],['plates are at potentials']], 'Ch11 Electrostatics','E=V/d plates','A')
rule([['ratio e2'],['2 μc'],['8 μc'],['e1 at a distance'],['produces an electric']], 'Ch11 Electrostatics','E ratio','A')
rule([['electric field at a distance r from a point charge'],['electrostatic field at a distance']], 'Ch11 Electrostatics','E∝1/r²','A')
rule([['copper is introduced']], 'Ch11 Electrostatics','Conductor between charges','C')
rule([['gauss']], 'Ch11 Electrostatics','Gauss law','A')
rule([['relative permittivity 2'],['permittivity 2']], 'Ch11 Electrostatics','Coulomb medium','A')
rule([['graph shows variation'],['with distance r from centre'],['with distance r from center']], 'Ch11 Electrostatics','Graph vs r','D')
rule([['electric field between them'],['-10v'],['+30v']], 'Ch11 Electrostatics','E=V/d plates','A')
rule([['force on a charge q in the electric'],['charge q in the electric field'],['electric field e']], 'Ch11 Electrostatics','F=qE','A')

# CH12 CURRENT
rule([['length and area of cross-section both are doubled'],['length and the cross-sectional area'],['area of cross section of a piece'],['cross-sectional area of a piece']], 'Ch12 Current','R=ρL/A','A')
rule([['wire of resistance'],['cut into'],['equal parts']], 'Ch12 Current','Cut wire n parts','A')
rule([['10 k'],['30 k']], 'Ch12 Current','Parallel product/sum','A')
rule([['three resistors of equal resistance']], 'Ch12 Current','Series/parallel','A')
rule([['heat dissipated']], 'Ch12 Current','Heat in parallel','A')
rule([['resistivity does not depend'],['resistivity of the material depends'],['resistivity of each part']], 'Ch12 Current','Resistivity property','A')
rule([['temperature of metal is increased'],['resistance of semiconductors'],['conductivity of a semi-conductor'],['conductivity of a metals'],['resistance decreases on increasing'],['resistance of a metal'],['rise of temperature']], 'Ch12 Current','R vs temperature','A')
rule([['temperature coefficient']], 'Ch12 Current','Temperature coefficient','B')
rule([['aluminum square rod'],['aluminium square rod']], 'Ch12 Current','R=ρL/A numeric','A')
rule([['resistance and volume of the conductor']], 'Ch12 Current','L from R,ρ,V','B')
rule([['battery of emf'],['internal resistance']], 'Ch12 Current','Internal resistance','C')
rule([['resistance of a motor'],['fan of resistance'],['240 v source']], 'Ch12 Current','Parallel current','A')
rule([['unknown resistance when connected with 8'],['8 ω in parallel'],['8 ohm in parallel']], 'Ch12 Current','Product/sum solve','A')
rule([['current in a simple series circuit is 5.0'],['drops to 4.0']], 'Ch12 Current','Same-battery equate','A')
rule([['emf of a cell depends']], 'Ch12 Current','EMF depends','C')
rule([['equilateral triangle']], 'Ch12 Current','Triangle resistance','A')
rule([['five identical cells'],['internal resistances']], 'Ch12 Current','Cells internal r','C')
rule([['drift velocity']], 'Ch12 Current','Drift velocity','C')
rule([['0.25 a'],['80 ω each'],['80 ohm each']], 'Ch12 Current','V=IR device','A')
rule([['200 v and 100 w'],['160 v']], 'Ch12 Current','Bulb P=V²/R','A')
rule([['1200 joules'],['12.5 ohms'],['12.5 ohm']], 'Ch12 Current','H=I²Rt','A')
rule([['kirchoff'],['kirchhoff']], 'Ch12 Current','KCL/KVL','A')
rule([['p(t) and w(t)'],['power p(t) and energy']], 'Ch12 Current','p(t),w(t)','A')
rule([['current through a circuit are doubled']], 'Ch12 Current','V/I doubling','A')
rule([['metallic wire remains'],['wire remains']], 'Ch12 Current','Wire neutral','A')
rule([['wire used in an electric heater'],['electric heater']], 'Ch12 Current','Heater wire material','C')
rule([['reciprocal of resistance']], 'Ch12 Current','Reciprocal of resistance','C')
rule([['equivalent resistance of the given'],['value of the current across'],['value of electric current and direction'],['part of an electric circuit']], 'Ch12 Current','Circuit diagram','D')
rule([['two conducting wires a and b'],['same material'],['length of b is twice']], 'Ch12 Current','R ratio','A')
rule([['resistivities ρ1'],['resistivities'],['equal length and different materials']], 'Ch12 Current','R ratio resistivity','A')

# CH13 MAGNETISM
rule([['solenoid']], 'Ch13 Magnetism','Solenoid B','A')
rule([['infinitely long straight'],['long straight wires'],['current is doubled']], 'Ch13 Magnetism','B wire ∝I/r','A')
rule([['radius of a circular current carrying coil'],['magnetic field at the centre of current carrying coil'],['radius is reduced to half'],['magnetic field intensity at the center'],['centre of current carrying coil']], 'Ch13 Magnetism','B coil centre','C')
rule([['concentric circular coils'],['coils of 20 turns']], 'Ch13 Magnetism','B coil centre','C')
rule([['e/m'],['charge per unit mass'],['ratio of q/m'],['q/m']], 'Ch13 Magnetism','e/m=v/Br','A')
rule([['radius of the path'],['charged particle of charge q and mass m'],['magnetic field is increased'],['curved path']], 'Ch13 Magnetism','r=mv/qB','A')
rule([['helical'],['parallel components']], 'Ch13 Magnetism','Helical path','A')
rule([['time period of revolution']], 'Ch13 Magnetism','T=2πm/qB','A')
rule([['cyclotron']], 'Ch13 Magnetism','Cyclotron','C')
rule([['kinetic energy remains constant'],['charged particle moves perpendicular']], 'Ch13 Magnetism','KE constant ⊥B','B')
rule([['magnetic force, experienced'],['force on a charge q in the electric'],['does not experience any force'],['no magnetic force']], 'Ch13 Magnetism','F=qvB sinθ','A')
rule([['wire of length 2 m'],['circular coil of single turn']], 'Ch13 Magnetism','m=NIA','A')
rule([['magnetic moment of a circular coil'],['magnetic dipole moment']], 'Ch13 Magnetism','m=NIA','A')
rule([['clockwise']], 'Ch13 Magnetism','Moment direction','A')
rule([['work done in rotating'],['rotating it by 180'],['rotating the bar magnet'],['deflected by an angle']], 'Ch13 Magnetism','W=MH(1-cosα)','A')
rule([['torque experienced by a magnetic dipole']], 'Ch13 Magnetism','Torque MB sinθ','C')
rule([['magnetic susceptibility'],['susceptibility (χ)'],['susceptibility']], 'Ch13 Magnetism','χ=μr-1','C')
rule([['not a ferromagnetic']], 'Ch13 Magnetism','Ferromagnetic materials','C')
rule([['curie']], 'Ch13 Magnetism','Curie temperature','A')
rule([['hysteresis']], 'Ch13 Magnetism','Hysteresis','A')
rule([['angle of dip']], 'Ch13 Magnetism','Angle of dip','A')
rule([['freely suspended magnet']], 'Ch13 Magnetism','Magnet NS','C')
rule([['flux density'],['length of the conductor']], 'Ch13 Magnetism','F=BIl','A')
rule([['parallel wires']], 'Ch13 Magnetism','Parallel wires force','C')
rule([['biot-savart'],['biot savart']], 'Ch13 Magnetism','Biot-Savart','C')
rule([['magnetic field at point'],['magnetic field due to the current carrying wire']], 'Ch13 Magnetism','B diagram','D')
rule([['magnetic field is perpendicular'],['charge per unit mass'],['electron is moving on a circular path']], 'Ch13 Magnetism','e/m=v/Br','A')
rule([['maximum work done'],['magnetic moment and magnetic field'],['angle between magnetic moment']], 'Ch13 Magnetism','W=MH(1-cosα)','A')
rule([['magnetic field inside a current carrying solenoid'],['interior of the solenoid']], 'Ch13 Magnetism','Solenoid B','A')
rule([['magnetic flux of the coil'],['magnetic field and number of turns']], 'Ch13 Magnetism','Flux BA','A')
rule([['two materials p and q'],['rise in temperature'],['diamagnetic']], 'Ch13 Magnetism','Diamagnetic with T rise','D')
rule([['electron','magnetic field','kinetic energy']], 'Ch13 Magnetism','Electron KE in B','B')
rule([['relation between the electric field and the magnetic field'],['e = b'],['e/b'],['e0'],['b0']], 'Ch13 Magnetism','E/B=c','A')

# CH14 EMI & AC
rule([['magnetic flux linked'],['flux linked']], 'Ch14 EMI/AC','ε=-dΦ/dt','A')
rule([['coil of an area 2'],['4 wb'],['8 wb']], 'Ch14 EMI/AC','ε=A dB/dt','A')
rule([['mutual induction'],['mutual inductance']], 'Ch14 EMI/AC','Mutual emf','C')
rule([['generator']], 'Ch14 EMI/AC','Generator EMI','A')
rule([['lenz']], 'Ch14 EMI/AC','Lenz','A')
rule([['faraday']], 'Ch14 EMI/AC','Faraday','A')
rule([['induced emf in a coil is given']], 'Ch14 EMI/AC','ε=-dΦ/dt','A')
rule([['50-turn coil'],['0.05 wb/s']], 'Ch14 EMI/AC','N dΦ/dt','B')
rule([['transformer']], 'Ch14 EMI/AC','Transformer','A')
rule([['half-wave rectifier'],['dc voltage across the load']], 'Ch14 EMI/AC','Half-wave Vdc','C')
rule([['alternating current is converted to direct'],['converted into direct current']], 'Ch14 EMI/AC','AC→DC','A')
rule([['rectifier'],['filter'],['regulator']], 'Ch14 EMI/AC','Rectifier order','A')
rule([['power in ac circuit'],['power dissipated'],['100 sin'],['average power in lcr']], 'Ch14 EMI/AC','AC power cosφ','A')
rule([['resonant frequency']], 'Ch14 EMI/AC','Resonant freq formula','C')
rule([['resonance'],['resonating'],['resonant']], 'Ch14 EMI/AC','Resonance','A')
rule([['pure inductive'],['purely inductive'],['phase difference']], 'Ch14 EMI/AC','Inductive 90°','A')
rule([['eddy current']], 'Ch14 EMI/AC','Eddy currents','C')
rule([['impedance of circuit'],['impedance']], 'Ch14 EMI/AC','Impedance','A')
rule([['rapidly toward the first coil'],['slowly toward the second']], 'Ch14 EMI/AC','ε∝speed','A')
rule([['energy stored in a 50 mh'],['inductor']], 'Ch14 EMI/AC','Inductor energy','C')
rule([['equivalent inductance']], 'Ch14 EMI/AC','Inductance combo','D')
rule([['maxwell'],['e0'],['b0']], 'Ch14 EMI/AC','E0/B0=c','A')
rule([['electric field and propagation vectors'],['magnetic field vector']], 'Ch14 EMI/AC','B=k×E/ω','A')
rule([['remains constant in an ideal step']], 'Ch14 EMI/AC','Transformer const','C')
rule([['half-cycle average'],['half cycle average']], 'Ch14 EMI/AC','Half-cycle average 2I0/pi','C')
rule([['primary coil'],['secondary coil'],['48 a'],['current in secondary']], 'Ch14 EMI/AC','Transformer turns','A')
rule([['induced emf'],['6t²'],['magnitude of induced emf']], 'Ch14 EMI/AC','ε=dΦ/dt numeric','A')

# CH15 EM WAVES
rule([['not an electromagnetic wave'],['not an em']], 'Ch15 EM Waves','Not EM wave','A')
rule([['do not transport'],["don't transport"]], 'Ch15 EM Waves','Carry energy not charge','A')
rule([['electromagnetic waves travel with a velocity'],['em waves travel'],['electromagnetic wave travel']], 'Ch15 EM Waves','c=3e8','A')
rule([['maximum wavelength']], 'Ch15 EM Waves','Max wavelength','A')
rule([['decreasing frequency'],['correct order of electromagnetic spectrum'],['order of wavelength'],['maximum frequency'],['minimum wavelength']], 'Ch15 EM Waves','Spectrum order','A')
rule([['angle between the electric component'],['electric and magnetic']], 'Ch15 EM Waves','E⊥B 90°','A')
rule([['ratio of the amplitude of the magnetic field'],['magnetic field to the amplitude']], 'Ch15 EM Waves','E0/B0=c','A')
rule([['incorrect about electromagnetic waves'],['incorrect statement regarding electromagnetic']], 'Ch15 EM Waves','EM properties','A')
rule([['electromagnetic waves carry']], 'Ch15 EM Waves','Carry energy','A')
rule([['propagation of electromagnetic waves is along'],['propagation of the electromagnetic']], 'Ch15 EM Waves','E×B direction','A')
rule([['propagating along the +z'],['+z']], 'Ch15 EM Waves','E,B,k representation','A')
rule([['wavelength range of microwave'],['wavelength range of visible'],['wavelength range']], 'Ch15 EM Waves','Wavelength range','C')
rule([['phase difference in electric and magnetic']], 'Ch15 EM Waves','E/B same phase','A')
rule([['electromagnetic wave moves from one medium'],['moves from one medium']], 'Ch15 EM Waves','Frequency constant medium','A')
rule([['permittivity'],['permeability'],['c, ϵ0'],['ϵ0'],['μ0']], 'Ch15 EM Waves','c,eps0,mu0 relation','A')
rule([['100 w light bulb'],['10%'],['visible radiation'],['intensity']], 'Ch15 EM Waves','Intensity I=P/4pir2','C')

# CH16 OPTICS
rule([['two mirrors inclined'],['inclined at 72'],['inclined at 30'],['number of images']], 'Ch16 Optics','Images two mirrors','C')
rule([['plane mirror']], 'Ch16 Optics','Plane mirror v=u','A')
rule([['running towards a plane mirror']], 'Ch16 Optics','Image velocity','B')
rule([['concave mirror'],['radius of curvature of a spherical mirror'],['spherical mirror formula'],['between the pole and the focus'],['shaving']], 'Ch16 Optics','Mirror formula','A')
rule([['power of a lens'],['+2.5 d'],['4d'],['convex lens of power']], 'Ch16 Optics','Lens power P=1/f','C')
rule([['converging lens']], 'Ch16 Optics','Converging lens','A')
rule([['double convex lens'],['radius of curvature of one of the surfaces']], 'Ch16 Optics','Lens maker','C')
rule([['concave lens with unequal radii'],['immersed in a liquid']], 'Ch16 Optics','Lens maker liquid','C')
rule([['magnification produced by a lens is negative']], 'Ch16 Optics','m sign','A')
rule([['glass slab']], 'Ch16 Optics','Frequency constant','A')
rule([['angle of deviation']], 'Ch16 Optics','Deviation mirror','C')
rule([['refractive index √3'],['glass surface of refractive index'],['60°'],['angle between the refracted and reflected']], 'Ch16 Optics','Snell numeric','A')
rule([['refractive index of glass is 1.5'],['wavelength in a vacuum is 6000']], 'Ch16 Optics','λ/μ','B')
rule([['wavelength of a light in a medium is 400']], 'Ch16 Optics','μ=c/fλ','B')
rule([['critical angle'],['total internal']], 'Ch16 Optics','Critical angle/TIR','A')
rule([['thin prism'],['prism angle']], 'Ch16 Optics','Prism δ=(μ-1)A','A')
rule([['dispersion']], 'Ch16 Optics','Dispersion','C')
rule([['rainbow']], 'Ch16 Optics','Rainbow','C')
rule([['maximum deviated'],['colour of light is maximum'],['refractive index of a material is greatest'],['refractive index is greatest']], 'Ch16 Optics','Violet deviates','C')
rule([['corona']], 'Ch16 Optics','Corona','A')
rule([['two slits spaced'],['third bright fringe'],['double slit']], 'Ch16 Optics','YDSE β','A')
rule([['width ratio of slit'],['ratio of amplitude']], 'Ch16 Optics','YDSE amplitude','C')
rule([['92 fringes'],['sodium light'],['number of fringes']], 'Ch16 Optics','Fringe count','A')
rule([['destructive interference']], 'Ch16 Optics','Interference phase','C')
rule([['huygens'],['huygen']], 'Ch16 Optics','Huygens','C')
rule([['necessary condition to observe diffraction'],['condition to observe diffraction']], 'Ch16 Optics','Diffraction condition','C')
rule([['resolving power'],['red light is replaced by blue'],['microscope']], 'Ch16 Optics','Resolving power','A')
rule([['microscope and telescope'],['telescope']], 'Ch16 Optics','Telescope','C')
rule([['simple microscope has a focal length']], 'Ch16 Optics','Simple microscope','A')
rule([['image formed on the retina'],['human eye'],['near point']], 'Ch16 Optics','Eye retina','A')
rule([['red colour paper'],['yellow light'],['appear as']], 'Ch16 Optics','Colour absorption','C')
rule([['polarized for reflection'],['reflected light is polarized'],['polarization'],['polarisation']], 'Ch16 Optics','Brewster polarization','C')
rule([['angle of refraction is larger'],['medium a to medium b']], 'Ch16 Optics','Snell denser/rarer','A')
rule([['refractive indices of glass and water'],['3 / 2 and 4 / 3'],['3/2 and 4/3']], 'Ch16 Optics','Velocity ratio v=c/mu','B')
rule([['erect image','mirror'],['erect image','30 cm']], 'Ch16 Optics','Erect -> convex mirror','B')
rule([['concave'],['-50'],['v = -50'],['image distance']], 'Ch16 Optics','Mirror formula numeric','A')

# CH17 DUAL NATURE
rule([['photoelectric'],['threshold'],['work function']], 'Ch17 Dual Nature','Photoelectric','A')
rule([['wavelength of photon'],['photon is 6000']], 'Ch17 Dual Nature','E=12400/λ','A')
rule([['de broglie']], 'Ch17 Dual Nature','de Broglie','A')
rule([['particle nature of light']], 'Ch17 Dual Nature','Particle nature','A')
rule([['2 ev'],['minimum energy required (in joules)']], 'Ch17 Dual Nature','eV→J','B')
rule([['threshold wavelength'],['5000'],['sodium']], 'Ch17 Dual Nature','Work function φ=hc/λ','A')
rule([['photoelectron is emitted'],['incident light is more than']], 'Ch17 Dual Nature','Threshold = frequency','A')
rule([['photoelectric','frequency']], 'Ch17 Dual Nature','Threshold frequency','A')

# CH18 ATOMS & NUCLEI
rule([['number of neutrons'],['atomic mass is']], 'Ch18 Atoms','Neutrons A-Z','A')
rule([['spectral lines'],['8th shell']], 'Ch18 Atoms','Spectral lines','A')
rule([['half life'],['half-life'],['decay constant'],['mean life']], 'Ch18 Atoms','Half-life','A')
rule([['penetrating power']], 'Ch18 Atoms','Penetration','A')
rule([['nuclear fusion']], 'Ch18 Atoms','Fusion','A')
rule([['nuclear reaction']], 'Ch18 Atoms','Decay balancing','C')
rule([['empirical formula']], 'Ch18 Atoms','Series name','C')

# CH19 ELECTRONICS
rule([['n-type'],['p-type'],['gallium'],['bismuth'],['antimony'],['phosphorus'],['doped'],['pentavalent'],['trivalent']], 'Ch19 Electronics','Doping N/P','A')
rule([['logic gate']], 'Ch19 Electronics','Logic gates','C')
rule([['zener']], 'Ch19 Electronics','Zener','A')
rule([['depletion']], 'Ch19 Electronics','Depletion','A')
rule([['absolute zero']], 'Ch19 Electronics','Ge at 0K','C')
rule([['heavily doped'],['region of a transistor']], 'Ch19 Electronics','Emitter doping','C')
rule([['current gain'],['β equals']], 'Ch19 Electronics','β=Ic/Ib','A')
rule([['n-p-n'],['p-n-p']], 'Ch19 Electronics','npn>pnp','A')
rule([['band in a solid'],['conduction']], 'Ch19 Electronics','Conduction band','C')
rule([['pn junction'],['p-n junction'],['insulator']], 'Ch19 Electronics','pn junction reverse','A')
rule([['and gate'],['not gate']], 'Ch19 Electronics','AND+NOT = NAND','C')

# CH20 COMMUNICATION
rule([['modulation'],['demodulation'],['message signal'],['baseband']], 'Ch20 Communication','Modulation','A')
rule([['radio waves'],['mode of wave propagation'],['wave propagation']], 'Ch20 Communication','Propagation modes','A')
rule([['sounded like that of a woman'],['sounds like'],['bandwidth']], 'Ch20 Communication','Wrong bandwidth','A')

# extra rules (v4)
rule([['two spheres of charges']], 'Ch11 Electrostatics','Coulomb numeric','A')
rule([['displaces a body']], 'Ch4 WorkEnergy','Dot product','A')
rule([['x = 2 + 5t'],['x = 2+5t']], 'Ch2 Kinematics','Polynomial s(t)','A')
rule([['moving with a constant velocity']], 'Ch13 Magnetism','Constant velocity -> E+B','A')
rule([['s = 5t2'],['s = 5t²'],['ratio of acceleration and initial velocity']], 'Ch2 Kinematics','Polynomial s(t)','A')
rule([['property remains same'],['travels from one medium to another']], 'Ch16 Optics','Frequency constant medium','A')
rule([['droplets merge'],['two small droplets']], 'Ch7 Bulk','Drops volume->r','B')
rule([['uniform chain']], 'Ch4 WorkEnergy','Chain on table','B')
rule([['q1and q2'],['exerted by q1']], 'Ch11 Electrostatics','F12 unchanged','A')
rule([['wets the glass']], 'Ch7 Bulk','Contact angle','A')

# MISC
rule([['distance between the galaxies'],['galaxies']], 'Misc','Galaxies receding','C')

# ---------------------------------------------------------------- classify
def classify():
    results=[]
    unmatched=[]
    for p,qid,q,a in out:
        ql=q.lower()
        if unit_dim(q):
            fam,st = u_family(q)
            results.append((p,qid,q,a,'Ch1 Units',fam,st)); continue
        hit=None
        for alt,ch,fam,st in R:
            if any(all(k in ql for k in g) for g in alt):
                hit=(ch,fam,st); break
        if hit: results.append((p,qid,q,a)+hit)
        else: unmatched.append((p,qid,q,a))
    return results, unmatched

if __name__=='__main__':
    res,un = classify()
    print("total:",len(res),"unmatched:",len(un))
    for p,qid,q,a in un:
        print("  ",p,qid,q[:100])
